Avoid test failure due to kroniak/ssh-client container permissions
kroniak/ssh-client:3.23 and kroniak/ssh-client:latest fail the
SSHAgentStepWorkflowTest#sshAgentDocker test with the message:

ERROR: Failed to run ssh-agent: ensure_mkdir: mkdir //.ssh: Permission denied
main: Couldn't prepare agent socket

I was unable to find a location where container issues could be reported,
so I set the container version to the last version that passed the test.